package space.rodionov.porosenokpetr.feature_driller.domain.utils

enum class StringTag {

    TOP_800_WORDS,
    TOP_200_VERBS,
    USUAL_WORDS,
    USUAL_VERBS,
    PHRASAL_VERBS,
    PHRASES,

    ITEM_COUNT,
    CURRENT_POSITION,
    ON_CARD_APPEARED,
    ON_CARD_DISAPPEARED,

    ACTIVE_CATEGORIES,
    ACTIVATE_ALL_CATEGORIES,
    CANNOT_TURN_ALL_CATS_OFF,


    COLLECTION,
    SEARCH_WORD,
    SEARCH_AMONG_ALL_WORDS,
    SEARCH_IN,
    PERCENTAGE,

    CATEGORY,
    WORD_IN_DIALOG,
    WORD_LEARNED,
    WORD_NOT_LEARNED,
    WORD_DESCROPTION,
    TRANSLATION_DIRECTION,
    FROM_FOREIGN_TO_NATIVE,
    FROM_NATIVE_TO_FOREIGN,
    DARK_MODE,
    FOLLOW_SYSTEM_MODE,
    APPEARANCE,

//    FROM_NATIVE,
//    TO_NATIVE,
//    FROM_SWEDISH,
//    FROM_ENGLISH,
//    FROM_UKRAINIAN,
//    TO_SWEDISH,
//    TO_ENGLISH,
//    TO_UKRAINIAN,

    SETTINGS,

    CHOOSE_TIME,
    NOTIFICATION_TITLE,
    NOTIFICATION_SUBTITLE,
    REMIND,
    REMINDER,
    NOTIFICATION_SCHEDULE_TITLE,
    NOTIFICATION_SCHEDULE_PATTERN,
    NOTIFICATION_SCHEDULE_ERROR,
    BTN_NEXT_TEXT,

    NATIVE_LANGUAGE,
    LEARNED_LANGUAGE,
    CURRENT_NATIVE_LANGUAGE,
    RUSSIAN,
    UKRAINIAN,
    NATIVE_LANGUAGE_SETTINGS,
    LEARNED_LANGUAGE_SETTINGS,
    LANGUAGE
}